# AdGuard 规则合并配置

# 广告过滤规则订阅
filters:
  - name: "AdGuard Base"
    url: "https://filters.adtidy.org/extension/chromium/filters/2.txt"
  - name: "AdGuard Chinese"
    url: "https://filters.adtidy.org/extension/chromium/filters/224.txt"
  - name: "SMAdHosts"
    url: "https://ghproxy.net/https://raw.githubusercontent.com/2Gardon/SM-Ad-FuckU-hosts/refs/heads/master/SMAdHosts"
  - name: "TT拒绝列表"
    url: "https://ghproxy.net/https://raw.githubusercontent.com/TTDNS/Cat/refs/heads/main/TT拒绝列表清单 (更新中).txt"
  - name: "去广告规则 - 酷安反馈反馈"
    url: "https://ghproxy.net/https://raw.githubusercontent.com/qq5460168/me/master/rules.txt"
  - name: "HyperADRules - Rules"
    url: "https://ghfast.top/raw.githubusercontent.com/Lynricsy/HyperADRules/master/rules.txt"
  - name: "NoAppDownload"
    url: "https://raw.githubusercontent.com/Noyllopa/NoAppDownload/master/NoAppDownload.txt"
  - name: "AWAvenue Ads Rule"
    url: "https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/AWAvenue-Ads-Rule.txt"
  - name: "自用规则3.0"
    url: "https://gitee.com/qiufengsf/ad---advertising/raw/main/自用规则3.0.txt"
  - name: "AdBlock Filter"
    url: "https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockfilters.txt"
  - name: "all.txt"
    url: "https://cdn.jsdelivr.net/gh/hululu1068/AdGuard-Rule@main/rule/all.txt"
  - name: "AdRules AdBlock List Plus"
    url: "https://adrules.top/adblock_plus.txt"
  - name: "混合规则(自动更新)"
    url: "https://jihulab.com/foreseeable_boy/adblock_auto/-/raw/main/Rules/adblock_auto.txt"

# 白名单订阅
whitelist:
  urls:
    - name: "去广告规则 - 酷安反馈反馈 Allow"
      url: "https://ghproxy.net/https://raw.githubusercontent.com/qq5460168/666/master/allow.txt"
    - name: "HyperADRules - Allow"
      url: "https://ghfast.top/raw.githubusercontent.com/Lynricsy/HyperADRules/master/allow.txt"
  # 直接配置的独立规则
  rules:
    - "@@||baidu.com^"
    - "@@||weibo.com^"

# DNS 过滤订阅
dns:
  - name: "AdGuard DNS Filter"
    url: "https://filters.adtidy.org/extension/chromium/filters/15.txt"
  - name: "DNS拒绝清单"
    url: "https://ghproxy.net/https://raw.githubusercontent.com/TTDNS/Cat/refs/heads/main/DNS.TXT"
  - name: "去广告规则 - 酷安反馈反馈 DNS"
    url: "https://ghproxy.net/https://raw.githubusercontent.com/qq5460168/666/master/dns.txt"
  - name: "HyperADRules - DNS"
    url: "https://ghfast.top/raw.githubusercontent.com/Lynricsy/HyperADRules/master/dns.txt"
  - name: "oisd big"
    url: "https://big.oisd.nl"
  - name: "AdBlock DNS"
    url: "https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockdns.txt"
